=== Specialized knowledge

This deployment guide requires a moderate level of familiarity with
AWS services. If you’re new to AWS, visit the
https://aws.amazon.com/getting-started/[Getting Started Resource Center^]
and the https://aws.amazon.com/training/[AWS Training and Certification
website]. These sites provide materials for learning how to design,
deploy, and operate your infrastructure and applications on the AWS
Cloud.

ifndef::production_build[]
_**This portion of the deployment guide is located at `docs/{specificdir}/specialized_knowledge.adoc`**_
[.preview_mode]
|===
a|
endif::production_build[]
include::../{specificdir}/specialized_knowledge.adoc[]
ifndef::production_build[]
|===
endif::production_build[]

=== AWS account

If you don’t already have an AWS account, create one at https://aws.amazon.com/[https://aws.amazon.com^] by following the on-screen instructions. Part of the sign-up process involves receiving a phone call and entering a PIN using the phone keypad.

Your AWS account is automatically signed up for all AWS services. You are charged only for the services you use.

=== EKS cluster

If you are deploying onto an existing EKS cluster that was not created by the Amazon EKS Quick Start, you will need to configure the cluster to allow this Quick Start to manage your EKS cluster. The requirements are detailed in Step 2 of the Deployment steps section of this document.


=== IAM permissions
//todo: scope of least-privilege
Before launching the Quick Start, you must log in to the AWS Management Console with https://docs.aws.amazon.com/IAM/latest/UserGuide/access_policies_job-functions.html[IAM permissions^] for the resources and actions the templates deploy.

The _AdministratorAccess_ managed policy within IAM provides sufficient permissions, although your organization may choose to use a custom policy with more restrictions.

=== Deployment options

This Quick Start provides two deployment options:

* *Deploy {partner-product-short-name} into a new VPC (end-to-end deployment)*. This option builds a new AWS environment consisting of the VPC, subnets, NAT gateways, security groups, bastion hosts, EKS cluster, a node group, and other infrastructure components. It then deploys {partner-product-short-name} into this new EKS cluster.
* *Deploy {partner-product-short-name} into a new EKS cluster in an existing VPC*. This option builds a new AWS EKS cluster, a node group, and other infrastructure components into an existing VPC. It then deploys {partner-product-short-name} into this new EKS cluster.
* *Deploy {partner-product-short-name} into an existing EKS cluster*. This option provisions {partner-product-short-name} in your existing AWS infrastructure. Note that when deploying into an EKS cluster that was not created by the Amazon EKS Quick Start there you must prepare the cluster as described in Step 2 of the Deployment Steps section of this guide.
